loopback0:
  ip: 40.40.40.40
  mask: 32
  description: Router4 Loopback0 Interface
loopback_ip_list:
  - name: Loopback1
    ipv4:
      - address: 41.41.41.41/32
  - name: Loopback2
    ipv4:
      - address: 42.42.42.42/32
  - name: Loopback3
    ipv4:
      - address: 43.43.43.43/32
loopback_description_list:
  - name: Loopback1
    description: Router4 Loopback1 Interface
    enabled: true
  - name: Loopback2
    description: Router4 Loopback2 Interface
    enabled: true
  - name: Loopback3
    description: Router4 Loopback3 Interface
    enabled: true
manual_config:
  gig2:
    ip: 172.10.1.2
    netmask: 255.255.255.252
    description: "Connected to R3 GigabitEthernet2 Interface"
  gig3:
    ip: 172.10.1.13
    netmask: 255.255.255.252
    description: "Connected to R6 GigabitEthernet3 Interface"