---
- name: Configure Loopback Interfaces
  hosts: ios_xe_routers
  gather_facts: false
  connection: ansible.netcommon.network_cli

  tasks:
    - name: Gather Interface information as structured data
      cisco.ios.ios_facts:
        gather_network_resources: l3_interfaces
      register: interfaces_pre
    - name: Display PRE Interface information
      debug:
        var: interfaces_pre.ansible_facts.ansible_net_interfaces
    - name: Configure Loopback0 interfaces on the network devices
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback0
            description: "{{ loopback0.description }}"
            enabled: true
        state: merged
    - name: Configure Loopback0 IP address on the network devices
      cisco.ios.ios_l3_interfaces:
        config:
          - name: Loopback0
            ipv4:
              - address: "{{ loopback0.ip }}/{{ loopback0.mask }}"
        state: merged
    - name: Gather Interface information as structured data
      cisco.ios.ios_facts:
        gather_network_resources: l3_interfaces
      register: interfaces_post
    - name: Display POST Interface information
      debug:
        var: interfaces_post.ansible_facts.ansible_net_interfaces