FROM ubuntu
RUN apt-get update &&\
    apt install python3 ansible openssh-client vim iputils-ping iproute2 -y
RUN useradd -m -s /bin/bash ansible && echo "ansible:ansible" | chpasswd && adduser ansible sudo
RUN sed -i "s/#   PasswordAuthentication /   PasswordAuthentication /g" /etc/ssh/ssh_config
 
EXPOSE 22