FROM ubuntu
RUN apt-get update &&\
    apt install python3 ssh vim iproute2 -y
RUN useradd -m -s /bin/bash client && echo "client:client" | chpasswd && adduser client sudo
RUN sed -i "s/#   PasswordAuthentication /   PasswordAuthentication /g" /etc/ssh/ssh_config
EXPOSE 22